### ISSUE TITLE
Duplicate settings in printer.cfg

### ISSUE THREAD

**Issue by manjaroblack** [danorder/Flsun-super-racer-Full-klipper-config-#2]
extruder section has duplicate settings:

[extruder]
step_pin: PD6
dir_pin: !PD3
enable_pin: !PB3
microsteps: 32
gear_ratio: 50:17	# CHANGE THIS TO WHAT APPLIES TO CUSTOM EXTRUDER THIS IS FOR BONDTECH / BMG CLONE  
rotation_distance: 24.963 #DEFAULT VALUE GET THIS FROM THE BONDTECH HOB GEAR. MEASURE THE HOB ON THE LEVER THAT VALUE x 3.14 = ROTATION DISTANCE. FLOW IN SLICER SHOULD BE WITHIN 10 PERCENT UP OR DOWN. FILAMENT TOLERANCE AND DENSITY WILL AFFECT FLOW ACTUAL FLOW. 
full_steps_per_rotation: 200 #CHANGE ME TO 400 FOR 0.9 DEGREE Steppers  ROTATION DISTANCE WILL AUTOMATICALLY BE CALIBRATED THIS APPLYS TO STEPPING AS WELL NO CHANGES REQUIRED. 
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: PE5
sensor_type: Generic 3950 #NTC 100K beta 3950 #reently fixed in latest klipper beta 3950 is dead. don't try to use a older version since the temp table is wrong by 15c. 
sensor_pin: PC1
_**min_temp: 0
max_temp: 300
pressure_advance: 0
pressure_advance_smooth_time: 0.0400
max_extrude_only_distance: 800.0**_
#control: pid
#pid_Kp: 15.17  # enable these and delete save at the bottom remember to run pid after setup. run fans 25-50 percent before running the command. 
#pid_Ki: 1.02
#pid_Kd: 56.27
_**min_temp: 0
max_temp: 300 #this value is set high for the purpose of hot tightening the hotend. stock hotends / tubes will degrade rappidly past 245. burning ptfe is also a neurotoxin. 
pressure_advance: 0 #set this from the slicer / fluidd / Mainsail. or start gcode its easier to do this in slicers with material specic gcode functions. 0.1-1.5 layer hight isn't usally benificial. 
pressure_advance_smooth_time: 0.040
max_extrude_only_distance: 800.0**_
instantaneous_corner_velocity: 2.5 # The equivalent of extruder jerk. this does not speed up pressue advance like linear adance 
step_pulse_duration:0

**Comment by danorder** [comment]
thank you pointing this out. surprised it didn't throw a  error .
