### ISSUE TITLE
Generic 3950

### ISSUE THREAD

**Issue by ibtaya** [danorder/Flsun-super-racer-Full-klipper-config-#3]
Line 146 
sensor_type: Generic 3950 #NTC 100K beta 3950 #reently fixed in latest klipper beta 3950 is dead. don't try to use a older version since the temp table is wrong by 15c. 

I had to use NTC 100K beta 3950, was this correct, fluidd couldn't recognize Generic 3950.

I am using the Nano v3

**Comment by danorder** [comment]
klipper wont  work / fludd will display  errors if you flashed a older bin file to the board. you have to run the make commands listed at the top of the config then flash via sdcard to get a "current version"  the one listed on mks website / others are more then likely out of quite far out of date.
